Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip
    sudo pip3 install psycopg2 django
  SHELL

  config.vm.synced_folder "./", "/vagrant_data"
end
